/* tslint:disable */
module.exports =
{
    "page": 1,
    "pageSize": 10,
    "pageItemCount": 10,
    "fullTextSearchItems": [
        {
            "projectId": 1,
            "artifactId": 72,
            "itemId": 72,
            "name": "New Process 1",
            "propertyName": "Name",
            "searchableValue": "New Process 1",
            "propertyTypeId": 32,
            "subartifactId": null,
            "isSubartifact": false,
            "itemTypeId": 76,
            "typeName": "Process",
            "typePrefix": "PRO",
            "createdUser": 2,
            "createdBy": "Jacob Harasimo",
            "createdDateTime": "2016-10-20T16:00:19.347Z",
            "lastModifiedUser": 2,
            "lastModifiedBy": null,
            "lastModifiedDateTime": "2016-10-20T16:00:19.347Z"
        },
        {
            "projectId": 1,
            "artifactId": 17,
            "itemId": 17,
            "name": "New Business Process Diagram 1",
            "propertyName": "Name",
            "searchableValue": "New Business Process Diagram 1",
            "propertyTypeId": 32,
            "subartifactId": null,
            "isSubartifact": false,
            "itemTypeId": 66,
            "typeName": "Business Process Diagram",
            "typePrefix": "BP",
            "createdUser": 1,
            "createdBy": "Default Instance Admin",
            "createdDateTime": "2016-10-17T19:57:50.587Z",
            "lastModifiedUser": 2,
            "lastModifiedBy": null,
            "lastModifiedDateTime": "2016-10-20T15:55:04.473Z"
        },
        {
            "projectId": 1,
            "artifactId": 16,
            "itemId": 16,
            "name": "New Actor 1 kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
            "propertyName": "Name",
            "searchableValue": "New Actor 1 kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
            "propertyTypeId": 32,
            "subartifactId": null,
            "isSubartifact": false,
            "itemTypeId": 67,
            "typeName": "Actor",
            "typePrefix": "AC",
            "createdUser": 1,
            "createdBy": "Default Instance Admin",
            "createdDateTime": "2016-10-17T19:57:50.587Z",
            "lastModifiedUser": 2,
            "lastModifiedBy": null,
            "lastModifiedDateTime": "2016-10-20T15:52:32.823Z"
        },
        {
            "projectId": 1,
            "artifactId": 20,
            "itemId": 20,
            "name": "New Domain Diagram 1",
            "propertyName": "Name",
            "searchableValue": "New Domain Diagram 1",
            "propertyTypeId": 32,
            "subartifactId": null,
            "isSubartifact": false,
            "itemTypeId": 74,
            "typeName": "Domain Diagram",
            "typePrefix": "DD",
            "createdUser": 1,
            "createdBy": "Default Instance Admin",
            "createdDateTime": "2016-10-17T19:57:50.587Z",
            "lastModifiedUser": 1,
            "lastModifiedBy": null,
            "lastModifiedDateTime": "2016-10-17T20:01:31.387Z"
        },
        {
            "projectId": 1,
            "artifactId": 14,
            "itemId": 14,
            "name": "New Document 1",
            "propertyName": "Name",
            "searchableValue": "New Document 1",
            "propertyTypeId": 32,
            "subartifactId": null,
            "isSubartifact": false,
            "itemTypeId": 72,
            "typeName": "Document",
            "typePrefix": "DOC",
            "createdUser": 1,
            "createdBy": "Default Instance Admin",
            "createdDateTime": "2016-10-17T19:57:50.587Z",
            "lastModifiedUser": 1,
            "lastModifiedBy": null,
            "lastModifiedDateTime": "2016-10-17T19:57:50.587Z"
        },
        {
            "projectId": 1,
            "artifactId": 19,
            "itemId": 19,
            "name": "New Generic Diagram 1",
            "propertyName": "Name",
            "searchableValue": "New Generic Diagram 1",
            "propertyTypeId": 32,
            "subartifactId": null,
            "isSubartifact": false,
            "itemTypeId": 71,
            "typeName": "Generic Diagram",
            "typePrefix": "GD",
            "createdUser": 1,
            "createdBy": "Default Instance Admin",
            "createdDateTime": "2016-10-17T19:57:50.587Z",
            "lastModifiedUser": 1,
            "lastModifiedBy": null,
            "lastModifiedDateTime": "2016-10-17T19:57:50.587Z"
        },
        {
            "projectId": 1,
            "artifactId": 18,
            "itemId": 18,
            "name": "New Glossary 1",
            "propertyName": "Name",
            "searchableValue": "New Glossary 1",
            "propertyTypeId": 32,
            "subartifactId": null,
            "isSubartifact": false,
            "itemTypeId": 63,
            "typeName": "Glossary",
            "typePrefix": "GL",
            "createdUser": 1,
            "createdBy": "Default Instance Admin",
            "createdDateTime": "2016-10-17T19:57:50.587Z",
            "lastModifiedUser": 1,
            "lastModifiedBy": null,
            "lastModifiedDateTime": "2016-10-17T19:57:50.587Z"
        },
        {
            "projectId": 1,
            "artifactId": 15,
            "itemId": 15,
            "name": "New Storyboard 1",
            "propertyName": "Name",
            "searchableValue": "New Storyboard 1",
            "propertyTypeId": 32,
            "subartifactId": null,
            "isSubartifact": false,
            "itemTypeId": 73,
            "typeName": "Storyboard",
            "typePrefix": "SB",
            "createdUser": 1,
            "createdBy": "Default Instance Admin",
            "createdDateTime": "2016-10-17T19:57:50.587Z",
            "lastModifiedUser": 1,
            "lastModifiedBy": null,
            "lastModifiedDateTime": "2016-10-17T19:57:50.587Z"
        },
        {
            "projectId": 1,
            "artifactId": 7,
            "itemId": 7,
            "name": "New Business Process Diagram 2",
            "propertyName": "Name",
            "searchableValue": "New Business Process Diagram 2",
            "propertyTypeId": 32,
            "subartifactId": null,
            "isSubartifact": false,
            "itemTypeId": 66,
            "typeName": "Business Process Diagram",
            "typePrefix": "BP",
            "createdUser": 1,
            "createdBy": "Default Instance Admin",
            "createdDateTime": "2016-10-17T19:57:50.587Z",
            "lastModifiedUser": 1,
            "lastModifiedBy": null,
            "lastModifiedDateTime": "2016-10-17T19:57:50.587Z"
        },
        {
            "projectId": 1,
            "artifactId": 8,
            "itemId": 8,
            "name": "New UI Mockup 1",
            "propertyName": "Name",
            "searchableValue": "New UI Mockup 1",
            "propertyTypeId": 32,
            "subartifactId": null,
            "isSubartifact": false,
            "itemTypeId": 70,
            "typeName": "UI Mockup",
            "typePrefix": "UM",
            "createdUser": 1,
            "createdBy": "Default Instance Admin",
            "createdDateTime": "2016-10-17T19:57:50.587Z",
            "lastModifiedUser": 1,
            "lastModifiedBy": null,
            "lastModifiedDateTime": "2016-10-17T19:57:50.587Z"
        }
    ]
};
